server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inspection_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: simple   # ✅ In-memory cache (no Redis needed)

jwt:
  secret: mysupersecretkeythatisverylongandsecure123456
  expiration: 86400000