server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inspection_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: simple   # ✅ In-memory cache (no Redis needed)

jwt:
  secret: mysupersecretkeythatisverylongandsecure123456
  expiration: 86400000

  spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_app_password   # ⚠️ NOT normal password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true